
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniproject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniproject-site
  template:
    metadata:
      labels:
        app: miniproject-site
    spec:
      containers:
        - name: miniproject-container
          image: shollynoob/minisite:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: miniproject-service
spec:
  selector:
    app: miniproject-site
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
